name: macOS Intel Build

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-macos-x64:
    runs-on: macos-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm install
      
      - name: Build
        run: npm run build:mac-x64
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          ls -la build
          echo "macOS DMG files:"
          find build -name "*.dmg" -type f
        shell: bash
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build-artifacts
          path: build/*.dmg 