name: Nightly Build

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm ci
      
      - name: build
        run: npm run build
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          ls -la build
          echo "Portable EXE files:"
          find build -name "*.exe" -type f
        shell: bash
      
      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: nightly
          name: Nightly Build
          body: |
            Automatically built nightly version - ${{ steps.date.outputs.date }}
            This version is built automatically based on the latest master branch code and may contain unstable features.
          draft: false
          prerelease: false
          files: |
            build/*.exe
            build/*.AppImage
            build/*.dmg
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/ 
