name: 日常构建与发布

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
      - 'release-*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm install
      
      - name: Build
        run: npm run build:win
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          dir build
          echo "MSI files:"
          Get-ChildItem -Path build -Filter "*.msi" -Recurse
        shell: pwsh
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: build/*.msi

  build-macos-arm64:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm install
      
      - name: Build
        run: npm run build:mac-arm64
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          ls -la build
          echo "macOS DMG files:"
          find build -name "*.dmg" -type f
        shell: bash
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build-artifacts
          path: build/*.dmg

  build-macos-x64:
    runs-on: macos-13
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm install
      
      - name: Build
        run: npm run build:mac-x64
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          ls -la build
          echo "macOS DMG files:"
          find build -name "*.dmg" -type f
        shell: bash
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build-artifacts
          path: build/*.dmg

  create-release:
    needs: [build-windows, build-macos-arm64, build-macos-x64]
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Create artifacts directory
        run: mkdir -p artifacts
      
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build-artifacts
          path: artifacts/windows
      
      - name: Download macOS x64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-x64-build-artifacts
          path: artifacts/macos-x64
      
      - name: Download macOS arm64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-build-artifacts
          path: artifacts/macos-arm64
      
      - name: List downloaded artifacts
        run: |
          find artifacts -type f
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: nightly-${{ steps.date.outputs.date }}
          name: 日常构建 ${{ steps.date.outputs.date }}
          body: |
            自动构建的日常版本 - ${{ steps.date.outputs.date }}
            此版本基于最新的主分支代码自动构建，可能包含不稳定的功能。
            
            ## 支持平台 / Supported Platforms
            - Windows Portable & Setup
            - macOS DMG (Intel x64 & Apple Silicon arm64)
          draft: false
          prerelease: true
          files: |
            artifacts/windows/*.msi
            artifacts/macos-x64/*.dmg
            artifacts/macos-arm64/*.dmg 