name: Windows Build

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Configuring nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Installation of dependencies
        run: npm install
      
      - name: Build
        run: npm run build:win
      
      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: List build directory contents
        run: |
          dir build
          echo "MSI files:"
          Get-ChildItem -Path build -Filter "*.msi" -Recurse
        shell: pwsh
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: build/*.msi